import json
from pathlib import Path
from playwright.sync_api import sync_playwright

OUT = Path('artifacts/presentation')
OUT.mkdir(parents=True, exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='msedge', headless=True)
    page = browser.new_page(viewport={'width': 1600, 'height': 1000}, device_scale_factor=1)
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto('http://127.0.0.1:8001/ui/operations')
    page.wait_for_function("document.getElementById('kWatch').textContent !== '-'")
    print('OPERATIONS', page.locator('#kWatch').inner_text(), flush=True)
    for name in ['automation', 'quant', 'performance', 'system', 'overview']:
        page.locator(f'[data-page="{name}"]').click()
        print('PAGE', name, page.locator(f'#{name}').is_visible(), flush=True)
    page.locator('[data-page="system"]').click()
    page.get_by_role('button', name='스케줄 저장', exact=True).click()
    page.wait_for_timeout(1000)
    print('SAVE', page.locator('#notice').inner_text(), flush=True)
    assert '저장했습니다' in page.locator('#notice').inner_text()
    original_schedule = page.locator('#schedule').input_value()
    page.locator('#schedule').fill('invalid')
    page.get_by_role('button', name='스케줄 저장', exact=True).click()
    page.wait_for_timeout(700)
    error_message = page.locator('#notice').inner_text()
    assert 'analysis_schedule' in error_message and '[object Object]' not in error_message
    print('VALIDATION_MESSAGE', error_message, flush=True)
    page.locator('#schedule').fill(original_schedule)
    page.locator('#notice').evaluate("el => el.classList.remove('show')")
    page.locator('[data-page="overview"]').click()
    page.screenshot(path=str(OUT / 'control-center.png'), full_page=True)
    page.goto('http://127.0.0.1:8001/ui/dashboard')
    page.wait_for_function("!document.getElementById('lastUpdated').textContent.includes('갱신 중')", timeout=90000)
    page.wait_for_function("!document.getElementById('stockDetail').textContent.includes('불러오는 중')", timeout=120000)
    print('DASHBOARD', page.locator('#lastUpdated').inner_text(), page.locator('#stockDetail').inner_text()[:200], flush=True)
    page.locator('#query').fill('삼성')
    page.get_by_role('button', name='검색', exact=True).click()
    page.wait_for_timeout(1000)
    print('SEARCH', page.locator('#results').inner_text()[:100], flush=True)
    page.locator('#ordersTab').click()
    page.locator('#holdingsTab').click()
    page.locator('#sellTab').click()
    page.locator('#buyTab').click()
    page.locator('#orderQuantity').fill('0')
    page.locator('#orderSubmit').click()
    print('VALIDATION', page.locator('#orderStatus').inner_text(), flush=True)
    page.locator('#orderQuantity').fill('1')
    page.locator('#orderStatus').evaluate("el => el.textContent = ''")
    page.screenshot(path=str(OUT / 'dashboard.png'), full_page=True)
    for route in ['dashboard', 'operations']:
        page.set_viewport_size({'width': 390, 'height': 844})
        page.goto(f'http://127.0.0.1:8001/ui/{route}')
        page.wait_for_timeout(3000)
        print('MOBILE', route, page.evaluate('document.documentElement.scrollWidth <= innerWidth'), flush=True)
        page.screenshot(path=str(OUT / f'{route}-mobile.png'), full_page=True)
    print('JS_ERRORS', json.dumps(errors, ensure_ascii=False), flush=True)
    assert not errors, errors
    browser.close()
